demo-core/main/default/objects/Demo_Project__c/Demo_Project__c.object-meta.xml
<CustomObject>
    <label>Demo Project</label>
    <nameField>
        <label>Demo Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Demo Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

demo-core/main/default/objects/Demo_Project__c/fields/Demo_Status__c.field-meta.xml
<CustomField>
    <fullName>Demo_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

demo-core/main/default/classes/DemoProjectUtils.cls
public class DemoProjectUtils {
    public static String getStatusMessage(Demo_Project__c project) {
        return 'Project ' + project.Name + ' is currently: ' + project.Demo_Status__c;
    }

    public static void logProjectInfo(Demo_Project__c project) {
        System.debug(getStatusMessage(project));
        System.debug('Logging: ' + project.Name + ' - ' + project.Demo_Status__c);
    }
    
    @InvocableMethod(label='Log Project Info')
	public static void logProject(List<Demo_Project__c> projects) {
    	for (Demo_Project__c p : projects) {
        	logProjectInfo(p);
    	}
	}

}